from __future__ import annotations

from src.sistema.validator import Validator

from typing import Final


ValidatorTuple = tuple[Validator, ...]


MODELO_1_UNIQUE_TITLES = (
    ('Cód RH da Unid.', 'Cod.Unid', 'Cód Unid.'),
    ('Nome Unidade',),
    ('Cód. Setor', 'Cód. RH Setor', 'Cod.Setor'),
    ('Nome Setor',),
    ('Cod.Cargo', 'Cód. Cargo', 'Cód. RH Cargo'),
    ('Nome Cargo',),
    ('Matrícula',),
    ('Cód. Funcionário', 'Cod Funcionário'),
    ('Nome Funcionário',),
    ('Dt. Nascimento', 'Dt.Nascimento'),
    ('Sexo',),
    ('Situação',),
    ('Dt.Admissão', 'Dt. Admissão'),
    ('Dt. Demissão', 'Dt.Demissão'),
    ('Estado Civil',),
    ('Pis/Pasep',),
    ('Contratação',),
    ('Rg', 'RG'),
    ('UF- RG', 'UF-RG'),
    ('CPF',),
    ('CTPS',),
    ('Endereço',),
    ('Bairro',),
    ('Cidade',),
    ('UF',),
    ('Cep',),
    ('Tel',),
    ('Naturalidade',),
    ('Cor',),
    ('E-mail',),
    ('Deficiencia', 'Deficiência'),
    ('CBO',),
    ('GFIP',),
    ('Endereço Unidade',),
    ('Bairro Unidade',),
    ('Cidade Unidade',),
    ('Estado Unidade',),
    ('Cep Unidade',),
    ('CNPJ Unidade',),
    ('Inscrição Unidade',),
    ('Tel1 Unidade',),
    ('Tel2 Unidade',),
    ('Tel3 Unidade',),
    ('Tel4 Unidade',),
    ('Contato Unidade', 'Contato Unid'),
    ('Cnae',),
    ('Número Endereço Funcionário', 'Número End. Funcionário'),
    ('Complemento Endereço Funcionário', 'Complemento End. Funcionário'),
    ('Razão Social da Unidade', 'Razão Social Unid.'),
    ('Nome da Mae do Funcionário', 'Nome da Mãe do Funcionário'),
    ('Cód RH Centro Custo.', 'Cod. Centro Custo', 'Cód Centro Custo'),
    ('Dt. Ultima Movimentação', 'Dt. Última Movimentação'),
    ('Cód. Unidade Contratante', 'Cod. Unidade contratante'),
    ('Razão Social',),
    ('CNPJ',),
    ('Turno',),
    ('Dt. Emissão CTPS', 'Dt.Emissão.Cart.Prof'),
    ('Série CTPS',),
    ('CNAE 2.0',),
    ('CNAE Livre',),
    ('Descrição CNAE Livre',),
    ('CEI',),
    ('Função',),
    ('CNAE 7',),
    ('Tipo de CNAE Utilizado',),
    ('Descr. Detalhada Cargo', 'Descrição Detalhada do Cargo'),
    ('Nº endereço Unidade', 'Nr Endereço Unidade'),
    ('Complemento Endereço Unidade', 'Complemento endereço Unidade'),
    ('Regime Revezamento', 'Regime de Revezamento'),
    ('Órgão expedidor do RG', 'Campo Livre 1'),
    ('Campo Livre 1', 'Livre1'),
    ('Campo Livre 2', 'Livre2'),
    ('Livre3', 'Campo Livre 3'),
    ('Telefone SMS',),
    ('Grau de Risco',),
    ('UF CTPS',),
    ('Nome Centro Custo',),
    ('Autoriza SMS',),
    ('Endereço Cobrança Unidade',),
    ('Número Endereço Cobrança Unidade',),
    ('Bairro Cobrança Unidade',),
    ('Cidade Cobrança Unidade',),
    ('Estado Cobrança Unidade',),
    ('Cep Cobrança Unidade',),
    ('Complemento Endereço Cobrança Unidade',),
    ('Remuneração Mensal (R$)', 'Remuneração Mensal'),
    ('Telefone Comercial',),
    ('Telefone Celular',),
    ('Data Emissão do RG',),
    ('Código do País de Nascimento', 'Código do país de Nascimento'),
    ('Origem Descrição Detalhada',),
    ('Unidade Contratante',),
    ('Escolaridade',),
    ('Categoria (eSocial)', 'Código Categoria (eSocial)'),
    ('Matrícula RH',),
    ('Gênero',),
    ('Nome Social',),
    ('Tipo de Admissão',),
    ('Grau de Instrução',),
    ('Nome do Pai', 'Nome do Pai do Funcionário'),
    ('Tipo de Vínculo',),
    ('Nome do Turno',),
    ('Texto Livre', 'Campo livre 4'),
    ('CPF Unidade',),
    ('CAEPF Unidade',),
    ('Tipo Sanguíneo',),
    ('Dt. Inicio Periodo Aquisitivo', 'Data Inicio Periodo Aquisitivo'),
    ('Data Fim Periodo Aquisitivo', 'Dt. Fim Periodo Aquisitivo'),
    ('CNO Unidade',),
    ('Desconsiderar para o eSocial',),
    ('Dt. Validade RG',),
    ('Desconsiderar Unidade para o eSocial',),
)

MODELO_1: Final[ValidatorTuple] = ()

MODELO_2: Final[ValidatorTuple] = ()
