from __future__ import annotations


class CertificateException:
    class TypeError(TypeError): ...

    class FileNotFound(FileNotFoundError): ...

    class FileExists(FileExistsError): ...


class ValidatorException:
    class RuntimeError(RuntimeError): ...

    class InvalidValueError(ValueError): ...

    class EmptyValueError(ValueError): ...


class Database:
    class InsertError(RuntimeError): ...

    class DeleteError(RuntimeError): ...

    class UpdateError(RuntimeError): ...

    class SelectError(RuntimeError): ...

    class ValueError(ValueError): ...

    class EncodeError(UnicodeEncodeError): ...

    class DecodeError(UnicodeDecodeError): ...

    class TypeError(TypeError): ...

    class SQLCheckError(RuntimeError): ...

    class PythonValidationError(RuntimeError): ...


class Task:
    class CannotCreateError(RuntimeError): ...

    class CannotRegisterStep(RuntimeError): ...


class Tkinter:
    class EventStateError(ValueError): ...

    class GlobalUndefined(NotImplementedError): ...

    class GlobalUnknown(RuntimeError): ...

    class GlobalAssigned(RuntimeError): ...


class SheetCell:
    class ValueError(ValueError): ...

    class TypeError(TypeError): ...

    class EmptyString(ValueError): ...


class SheetColumn:
    class ValueError(ValueError): ...

    class TypeError(TypeError): ...

    class EmptyString(ValueError): ...


class SheetParsing:
    class ValueError(ValueError): ...

    class TypeError(TypeError): ...

    class EmptyString(ValueError): ...

    class IndexError(IndexError): ...


class App:
    class BootstrapError(RuntimeError): ...
