name: Format Code
on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      # Installing dependencies
      - run: npm install -g prettier
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Running job
      - run: |
          ruff check --silent --select I --fix .
          ruff check --silent --select F401 --fix .
          ruff format --silent .
      - run: |
          python scripts/format_json.py **/*.json
          yamlfix **/*.yaml
          taplo format '**/*.toml'
      - run: prettier --log-level silent --write **/*.jsonc
