name: Format Code
on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      # Installing dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # format python
      - run: |
          ruff check --silent --select I --fix .
          ruff check --silent --select F401 --fix .
          ruff format --silent .
      # format config files
      - run: |
          python scripts/format_json.py **/*.{json,jsonc}
          yamlfix **/*.yaml
          taplo format **/*.toml
