name: Pylint
on:
  push:
  pull_request:
    types: [opened, reopened, edited, converted_to_draft, ready_for_review]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci-requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
