name: Ruff
on:
  push:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, converted_to_draft]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci-requirements.txt
      - name: Run Ruff
        run: ./hooks/ruff.sh
